<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework3</span></h1>
</div>
<div class="row">
   <a href="<?php echo $this->url('post', ['action' =>'add']); ?>">Add</a>
    <table class="table">
      <thead>
         <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
         </tr>
      </thead>
      <tbody>
         <?php
         if(count($posts)>0):
            foreach($posts as $post):
               ?>
               <tr>
                  <th scope="row"><?php echo $post->getId();?></th>
                  <td><?php echo $post->getTitle();?></td>
                  <td><?php echo $post->getDescription();?></td>
                  <td><?php echo $post->getCategory();?></td>
                  <td><a href="<?php echo $this->url('post', ['action' =>'view', 'id' => $post->getId()]); ?>" class="label label-primary">VIEW</a></td>
                  <td><a href="<?php echo $this->url('post', ['action' =>'edit', 'id' => $post->getId()]); ?>"  class="label label-default">UPDATE</a></td>
                  <td><a href="<?php echo $this->url('post', ['action' =>'delete', 'id' => $post->getId()]); ?>" class="label label-danger">DELETE</a></td>   
               </tr>
               <?php
            endforeach;
         else:
         ?>
         <tr>
            <td>No records found</td>
         </tr>
      <?php endif; ?>
      </tbody>
    </table>
</div>

