<?php
   $title = 'VIEW Post';
   $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<ul class="list-group">
	<li class="list-group-item align-items-center">
		<span>Title : <?php echo $post->getTitle(); ?></span>
	</li>
	<li class="list-group-item align-items-center">
		<span>Description : <?php echo $post->getDescription(); ?></span>
	</li>
	<li class="list-group-item align-items-center">
		<span>Category : <?php echo $post->getCategory(); ?></span>
	</li>
</ul>
<div class="row">
	<a href="<?php echo $this->basePath('/'); ?>" class="btn btn-primary">BACK</a>
</div>

